# kubectl get configmap aws-auth -n kube-system -o yaml 
# aws sts get-caller-identity
# aws eks update-kubeconfig --region us-east-1 --name roboshop


apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::453531893439:role/eksctl-roboshop-nodegroup-spot-ng-NodeInstanceRole-BUXqxw2hW90K
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      userarn: arn:aws:iam::453531893439:user/trixie
      username: trixie 
      userarn: arn:aws:iam::453531893439:user/sumathi
      username: sumathi 
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: e813e3f2-fccf-4c1b-bbfc-92443267e213